language: php

php:
- 7.0

env:
  global:
  - secure: "SJWBBIE4So2FJiBvR466Pl3MS3heU1FtYPxF7RBQ/DdA3iHkR9ck5hQB3+Kk+VxxSxFapC6NE4l1VKkxsZvigkQckP+8UWw1WEd7EqseRFmFmB2z1m0V/W4QWHZwVEmmrrjCKtY2JkfN5RLawGXghnfPGTceJMdcvoClXlAj9NfnYXYpwdJVOekkZaKLMGbTznH3icu4lgpHPFgayJ7T8sdiseU6kRMFkrT3AApi1k2PZjkmrEQP9RftTCJnX/rzBZPY3XLW6as06T3tSJuv/e9zdPjJP7OWMZcArLSsPn0G2g7ydafusupndTEJ/MClLfG8sRImvNGsy0cin3ybATEVLuiQMHINJ5/Qw5bi6WVRkhQrp6mSy5vjQq9WF0hwzran7XU7DhJebguFyGB7mXX4AC9c55B837UIBW8UDF8D2tXrr0ZUZ4ZiikETw00LQUFU1BM/ESSV8QIhzdm+E8GvOw7tLDmWIarMtHS0RAKnaIC99Fm67Ggf/lqo0+L5REv5/hBco0a5ehZYjase6fCqaVuPxKIfKP8XBIF06YgIDCWlrv3isS4gqK9pMCJg93ayJiTPFAhDvp5KDr9IeCKt+H9nLFuggrI4UtYQ8m9L/kzR+vtS8lcFPp5qimZhfe+sykeo+OWFt8FS8NANpimynmdoSLUEN7+Jv8IwcE8="
  - secure: "YPwY8gVWvdtl8fpmD55ksm/jwlLlfqhz9N33inacPExzMcxvg60aoIqlidtAGzcmazul2l6VYhH8fNBDttHZfD1trd+Kk0ZFOZJdT+qulhNzGp2RwdQfhuXXK7ys9C4eDMGrLTqbQ7hAHB2RUAB8sdOMcNoCaczqNYOViZDT7iT87cMUTqEzHZtsQZB3F0s+GSt9c/0/qIqWZzqNzomqUQ2jsZlXGnlYmly08B4sZEI4QaHOCMRhavsR3y7QYJOUnRd8daKnYWiBiZZgS3x9Xfzi/UtVzFl6H7yAHTpfN5NbK15NNxXNAglPU2XGjTNCmClEJufguFNMw6vigjrS0ILze/57aLd2iD7kY3VgtcQpjb2w00FFx1I+bvUyzJ4f4T4BWr635SFbmabnAfcXr/3kojgUjjnH6iIng9FhASHVbb2Y2RKn5w+e/9cMe0CrOifoOcb6dRhd6HIDjtszPG5Sw9SrOaHKh6PUSUiS0G+I/UbZg2o+EB26mnjFwMWIsrSvHZgYsI2jgqTI5ro6WCt6atDmJ5vjbosHR5kHiJS//Ur7X7hpv4Er1ZfE5mLD8QPXKpW0FNtmf/62r+hGRHowchFW6acj2m1v9hmgiYR89ZTs9PjJlyHF2NxPasUS+tCjmjbOCsJAM/EPYY4S7HEjKVldTPcJgz54iDisiwg="
  - secure: "cRqCHcekloccuaAv+o6RW12WfIuMZzz4Baw2bOmT8kBdhZdwjqPckG3VkGRPrfxGa8PQ+NF9BLYxu+O+GgaNDzjCtl1A9Nb6mKLoUo8vkzxR/QSwnfcLPBlpS4ECzHoLaFRN3/hVuh8SgX3FRa4IbiEhBt7YcIedjGZZYkTGlIRx1WTUoE0LNL8jr5vHNL3vgwbTkkfiGmQBvBRRZaSMqvGx9on2VXeedZqxfFDSw7LtRCZ8N7m1DeN14qfz66shr9a4m4RZ198bCQJRoeYdFjrDtgWd2STqAKMG4xmuEc/mwvbsxt2BaEFony+19knmTXuq1OSbGXCySQz09kY8FtIfUdj1Vw6RpVsCvZZUxEnse26cEIVrwroYA5SI9IdFxhyhE2+W1C0Q+FcSYO20BaLrSe+uf0Z4TWvra9D96RyE/56zxGr9d4HSq+EFYODBtSo1a7GrwcrjMhFdOw+l3h/tjfUQqc5/u0Tq0J39ch7yOtK0iXd0xj8I0PqxxVvJpE6kBLmxy5FUxY3gvoEthRPOa2hgftrVCUNjfeNj4KZFaalh/gkf0mp8UdQbBELWck72qrYPIJFhlF7d9BL6WceVHQ81O3E7rWXe6pxf+vx/whtbJTYKpIFzd8rGkYcOxCa9g1CzLIMnlQgihJpJZm8hzdml7SNHSGECdevjZMw="
  - secure: "yu728XCf5PpYYn7qZquEmYnrzT7adXu6F9yh6s2kaWtIj7LnSx74+JdNDvzNYXoX2D1HIfk3CJg2HVJ9hkkdXRzZbm1iStWmTjN0+Ozq6BT2HFw/h1gHDj6x1xwxssg216jL/6bXe7igHQX88+WDj9FRqJ8sVIXfhUxZPi3ZsSIePAia4LXlxX29wUKxPlfB0iDFFajVzZDrhhrbw/W/nORY9xNb0mEFy4dxEE6xue1sC6mD7TWBkW1iKUQ3oaw9uRUKeZU717Z9sEyGn66Urtpl4VklUxgeNkULn+ts0nHQ8pKVsh0ASQlkw6huuft18NEzf+p5fGoNzNV6GJ70zAg3+7WjnJvDSOc/1jm2/x3iBao43CSR8HA5GFlHJqENqDcFM6aO2DbWrnMy/qdx12TGCOTETVUZHKTHoD01uDinzrZU+bPqdJ8wbyXkExGQ0kOtYuW6SHFKXy90rnWtZLYZLIGbGMquy3j1G0uCm+6v+lTlA2BEJFW5AHZ/J8ACxjmxYLS23wIlB6yN5HiBK289Ua7koLrXeEekFmNSQZT/C/M7GPxLbCcX7ALWTfGu/IgCOcNTRxoXvtUiIZNb08EejskLmVjtMyEH4YKgK5nhD39wMoL7T/C2iRtDc/1E3JTQlWKrOb/AEKEIKQnQlqt4uTUrhamP39FuYLD/0x4="
  - SYMFONY_VERSION="3.0.*" DB=mysql

cache:
  directories:
  - "$HOME/.composer/cache/files" 

before_script:
- composer install --prefer-source

script:
- phpunit

addons:
  apt:
    packages:
    - sshpass 

after_success:
- mkdir build
- mv * build
- tar -czf package.tgz build
- export SSHPASS=$DEPLOY_PASS
- sshpass -e scp package.tgz $DEPLOY_USER@$DEPLOY_HOST:$DEPLOY_PATH
- sshpass -e ssh $DEPLOY_USER@$DEPLOY_HOST $DEPLOY_PATH/deploy.sh    

sudo: false

notifications:
  email: slimbachiya@officebrain.com
