language: php

php:
  # Test against the given PHP version ...
  - 5.6

# Define an environment variable
env:
  - SYMFONY_VERSION="3.0.*" DB=mysql

# Cache composer packages so "composer install" is faster
cache:
  directories:
    - $HOME/.composer/cache/files  

# Update composer
before-install:
  - composer self-update

# Install composer dependencies,
# Create database, schema and fixtures
install:
  - composer install
  - cp app/config/parameters.yml.dist app/config/parameters.yml

# Run script
script:
  - phpunit

# Allows use container-based infrastructure
sudo: false  

# After a build, send email notification with the build results
notifications:
  email: false
