language: php

php:
- 7.0

env:
- SYMFONY_VERSION="3.0.*" DB=mysql

cache:
  directories:
  - "$HOME/.composer/cache/files"

before-install:
- composer self-update

install:
- composer install
- cp app/config/parameters.yml.dist app/config/parameters.yml

script:
- phpunit
- gulp --production

addons:
    apt:
        packages:
            - sshpass

DEPLOY_HOST=162:
  '209':
    '122':
      '251':
        secure: Mp8y+Swnv8b5yaMmtegv07TrIaVv3OdNd1IK2XTQ2W0nl/GjmD0Y2eWzvuixyY2rVCaQxF88Fak0Fbn5gsSsY0PkJbwViXftIdQuid6VEMiQEYlTqgmjW0CbienVT15khD+xLzdpmT3HBo4SC/+37TrrZqRmJeW76dtvZZeU2+cSIW6mfnrIt+JX2Vu6BdkrLTdFMe0WRKytdtmVAoOfxZ7xw0lg9kFR64oCox45PenFndU3NNxZHMYzAe4Gu0cJIHowiol+HXsHAozi8ZUbwGM9uu6JjMvjIy/wLQUe6axrOaPMtv/1xIz2lw2/mZU5o8rASswAjZrFXUMOIO+qFf/Prdod289zbBpP66dwp6euN0XXftWnW39au45BBd9umEP/jwVOh70xpQI1dbIhKEPVAbNBMn/3eaKyilasGwVTaaW2BKUrlS/U7FUCwRIXto3RWkDrojbM6Hcnr1z2FSr/v6CTCCktYuNNkEwvNV/8o6BVsA77c6VkV9AMKptrKUK4vBOwi74jHEL9bH1lzjNsZg/Ff9Dp7/id3VAZEpbo8AmO83yrQ04Eds2nHWOHnAWnoz6rd8NYKFkm3vRwemJdHekyeKPo26uamG17wblGCxM+49x30rQAblVojz3HxQhR5EPffxqsMP1mjI0L6N+qAhBQn6fuAtYdeMCux+s=
DEPLOY_PATH=/var/www/html/testci:
  secure: rv+o/64o615Lfjrc/7ZME/lhKK7gpB7gqoot/rQBn8eP2vIowO7cNrzM38P7sLZt+Z0MSeqisliEzS/V+MGtbp1GjPe0v/rlobIFzyo6b6XcjA1+c17JybFplle4Kdheu5st4z/+AIw40TF2RPWbssBtb5/T6DgJtRJpsoeuv+VG6CVsLXx7PW9eS5nsTSqmTTd+sw1MXeiiNjj91wIQXVpYtnQkHqDXFu2f02C6lLcC8qjV/KnfeAKx8Rco++8oTZkiylR5aEYB5Pr0TQ1nOIS0QvsZMFh4kQGdTOYe951PK8qMT/3ujXsbjXbfL8igKpuOmYoNrGDeuHS1RsoCBZdnnXtBdxpjPq44jqeGJi2hM+0GtECgaPzGU9Bz0IpqWXmTx7LVRSpBEE66Dg6J2QwDzo366T18sOEYOGkQ31qXOSRvTHdZuu1MlIWJ2addHSdIRYmCyBTISjSJAIff83YxfqiXenH4hqaXTtC3lTgpQeZ3oB3cVYpFOzPjWQRVbHG5jjdbO9c6+5GS6ubDgdxyjlqc+nkrcTsBgWlyp24jfUQpSmndW+sMOBzIqDd+PQuS4jgZOiUH7U7AJp6ZLEHRz9A4hZK/nPs4xxoKyA66u4TX1HQqngxUcZMyRhhFBdy/OCuFjpKY4vRl47a1W3q9QqvfBILENYgeQwiq5Fc=
DEPLOY_USER=softdev:
  secure: LX3n7gSgvN5wG74pKqz6i5DuVXC3yPT3sP0vio+1F/PrxCwzyE9u9uW/lLRxeUKBw66BJz+rkPJpu3Qlr+5E3xOH9Y0psy8QFOGO8rcVX6UodTIKFTr2GKcOsRN1HrLyt9KqZQWUiFlSNrub0ReA1glV0i1iTAK1Y0I9YKe3K5BYiOWS70GzRcL6tbDvs/M6tNtoB3ZTgBWWnYa0oSzFjf0TSlRE/yiq217kWHUSZzPTkns8JhVeqGZRDsjz2zTY9NWqPNAsmiSTjnBm2bxmBkt9K7KnfCWKH/DU5hkMWk1GFESTFMkuCtNSAIj4oF53TV5IzqIFpitGX+X955kpT8axGgaCSaLynlSVRUMwtMqYzRKVye3EWv+WLoHz/o0J6XGLBUZB8lgxkuZvMS37iku/ofY7znEEqrv+hTNUf0UgHIVD30eQesCEnXqys0juadcCPRCxMvQMAeS7fWaLPfGfZvsUD+5KnHU9BNi/6wG/XQgCBGp3mYkrllqkX7+0sHes5MxWNVmJ9GCCJmkQs2EjYBrKx3geVqjCPksJkwLtwJmjYCjFl0r2mOCnh5PFJMmeNPt1/MGru9Uq3+IjE5xQQE1nuevIi+C+GuLTSDEsM7La1iIirkO4J2IyuNdhFqaFr1j2raXgY8RvwDaDM8yM8NxkHWDK4j1uOa3N5Sk=
DEPLOY_PASS=rAb@2Ufr3Xes!Uf:
  secure: wctClVG0nWgnpK5z+HuTY3TKEEyR606FB2MK8u1I8mQ0pBi9IPPRYYwUMOSM032jybJv+rmBeIR28MAhQCGasdxNx/Y9l/QBDD+/3BI3bMIsKmZyqUex7Bk8VLtNM9eRctcCmEyvXb6m6+5DzmlWtiQvTg8IDzVOZjYGIKQRmx5IaZRtRXD3+ZFt/lvepGPTaTmpuwTCsOT9FqlCIrX7ilRjYM082bohgteAV2bcdKGttv313Fldytm8KBO5addsc5RvvDai5K3RUhYAGeYLiqVd4N8WMvV2aCMNgWlum1fguhssGrCswe0qicGfT8xYIFHemdin7mSXjFbOHy0vGrPpfqu9Pe5JX8N5F/O2+/pz/LvkCAillIMj6fQQkQbYDWL/x/5BK/FHfhAV+5CMJoLABQzr1vzfYf2wIoGGHHi2XsiemxQ5l/W44AFqigi2vkdmsY0t6dFnOtkMoKHYf5kP16TOKFzoUYMlP/OTb6VoCyW+KlO3hnn9LWvTmA0Kebc1FXf5huFZQZZ9QdzoZb5IFzem1KROgCbL1GYd3Yyp6QpPOnYOayOdbDNiZ5ubRRHfQQY0eLhQ1dcfsX1jpRTYvN+2Gl+8Op57cWVPalnneMqZqXDMeGeS+sVP6TLDOUA/s0jTocbYH7MpxUhG2iyuQTxh7A66AZTrqZnipTM=

after_success:
    - mkdir build
    - mv * build
    - tar -czf package.tgz build
    - export SSHPASS=$DEPLOY_PASS
    - sshpass -e scp package.tgz $DEPLOY_USER@$DEPLOY_HOST:$DEPLOY_PATH

sudo: false

notifications:
  email: false
