language: php

php:
- 7.0

env:
- SYMFONY_VERSION="3.0.*" DB=mysql

cache:
  directories:
  - "$HOME/.composer/cache/files"

before-install:
- composer self-update

install:
- composer install
- cp app/config/parameters.yml.dist app/config/parameters.yml

script:
- phpunit

addons:
    apt:
        packages:
            - sshpass
after_success:
    - mkdir build
    - mv * build
    - tar -czf package.tgz build
    - export SSHPASS='rAb@2Ufr3Xes!Uf'
    - sshpass -e scp package.tgz softdev@162.209.122.251:/var/www/html/testci

sudo: false

notifications:
  email: false
